version: "3.7"
services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sms
      MYSQL_USER: sarra_ilef_arij
      MYSQL_PASSWORD: forppp
      MYSQL_ROOT_PASSWORD: forppp
    restart: on-failure
  sms:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    
 